### PR TITLE
removed build files from repo and updated gitignore

### LINKED ISSUE #31: Remove build files from the repo
Remove the build files from the repository and update the `.gitignore` to ignore them in future commits

### PR DESCRIPTION
**Pull request by aaronbarnardsound**
fixes #31

### CODE REVIEW

**Comment by cmeisl** [comment]
Does this remove the entire `/lib` directory from the repo? We want to keep the `/lib/images directory in the repo.

**Comment by aaronbarnardsound** [comment]
> Does this remove the entire `/lib` directory from the repo? We want to keep the `/lib/images directory in the repo.

This just removes the build files and makes git ignore the whole `lib` folder.

**Comment by cmeisl** [comment]
But we don't want to ignore the images. Those should be under version control.

**Comment by aaronbarnardsound** [comment]
No worries, will update the `.gitignore` to specifically ignore just the build files 👍

**Pull request merged**
