### PR TITLE
Custom notifications

### LINKED ISSUE #114: Should be able to call assist.notify
I want to be able to create an assist-styled notification on-demand, so I can respond to events in the dapp context and show my own contextual notifications.

### PR DESCRIPTION
**Pull request by liamaharon**
Closes #114 
- Allows passing a `customTimeout` param to notificationUI events
- Allows the developer to trigger custom notifications

TODO: 
- [x] Specify entire function signature in documentation
- [x] Improve example showing using dismiss function
- [x] Add tests to verify there are no errors when calling the dismiss func after the notification has timed out and vice versa
- [x] Fix success customTimeout not working when value is `-1`
- [x] Mention that custom HTML can be embedded into the message
- [x] Show timer in pending type notification
- [x] Add integration tests for new types of event 
- [x] Move `customTimeout` into an options param

### CODE REVIEW

**Comment by liamaharon** [comment]
- Specified correct function signature in documentation
- Improved dismiss function example
- Added tests to verify there are no errors when calling the dismiss func after the notification has timed out and vice versa

**Comment by cmeisl** [comment]
Testing with customTimeout of -1 (i.e. no timeout) works as expected for `pending` and `error`, but `success` is still automatically dismissed.

Is there a reason not to include the timer UI for `pending` notifications?

**Comment by liamaharon** [comment]
1. Good catch, will fix and add some tests for the custom timeout functionality.

2. I don't see why not, will take a look at getting the timer shown.

**Comment by liamaharon** [comment]
Replaced by #133

**Pull request closed without merging**
